### ISSUE TITLE
Allow the fake client to mock server API error responses

### ISSUE THREAD

**Issue by LCaparelli** [m88i/nexus-operator#105]
Today we have the following implementation for the fake client used in testing, taken from `pkg/test/client.go`:

```go
// NewFakeClient will create a new fake client with all needed schemas
func NewFakeClient(initObjs ...runtime.Object) client.Client {
	return fake.NewFakeClientWithScheme(GetSchema(), initObjs...)
}

// GetSchema gets the needed schema for fake tests
func GetSchema() *runtime.Scheme {
	s := scheme.Scheme
	s.AddKnownTypes(v1alpha1.SchemeGroupVersion, &v1alpha1.Nexus{})
	s.AddKnownTypes(routev1.GroupVersion, &routev1.Route{}, &routev1.RouteList{})
	return s
}
```

While this is nice and really useful, it doesn't allow us to mock specific responses to certain events/actions. That feature would come in pretty handy when testing the resource managers' ability to handle/report errors when the server responds, for example, with a 500 status code.

Digging up some docs I found that `k8s.io/client-go/testing` (which is already a dependency for the project) has a nice fake client implementation that allow us to insert "interceptors" (called `Reactor` here) that allow us to define how the fake client should respond to certain actions.

Check out its [godoc](https://godoc.org/k8s.io/client-go/testing) for all the good stuff and [this issue](https://github.com/kubernetes/client-go/issues/500) for an example of working usage.

Also noteworthy is that our fake discovery client uses the `k8s.io/client-go/discovery/fake` package, which is built on top of the same `Fake` [implementation](https://github.com/kubernetes/client-go/blob/5b8ea8e61cb840f5c6f6baacd67ae93fe30a3027/testing/fake.go).

**Comment by LCaparelli** [comment]
What do you think @ricardozanini @Kaitou786? :-)

**Comment by ricardozanini** [comment]
Please also send a PR to the Kogito Operator once we finish this implementation here. :)

**Comment by LCaparelli** [comment]
Unfortunately things are not so simple. The operator-sdk builds on top of the of [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). Most notably in this context, it builds on top of the [Client interface](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L104).

[client-go](https://github.com/kubernetes/client-go/) is the one that offers the `Reactor` we were going to use, but does so through a [Clientset](https://github.com/kubernetes/client-go/blob/31e286ee1926a84e0bfd4c8c8c77b3816f98244a/kubernetes/clientset.go#L115), which does not implement this interface on which the operator-sdk heavily relies on.

Which made me wonder if there's no demand on `controller-runtime` for this feature, which seems pretty useful in testing. I eventually found [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/72) which requests exactly what we're discussing here, but it would seem that at least for now there is no interest in supporting this.

With that in mind I propose we instead wrap the fake client in a structure that allows to control whether or not that request should result in an error (and in which error), which is a similar approach to that taken by at least some other projects which were looking for this feature and commented on that issue from `controller-runtime`.

@ricardozanini @Kaitou786 hate to bother again so soon, but let me know your thoughts.

On a related matter: [controller-runtime's doc](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/client/fake) mentions that this fake client we've been using has been deprecated, but it seems this was recently reconsidered according to [this issue's](https://github.com/kubernetes-sigs/controller-runtime/issues/768) latest developments. We ought to keep an eye out for anything new regarding this.

**Comment by ricardozanini** [comment]
@LCaparelli we already encapsulate `client-go` and `controller-runtime` clients in the Kogito Operator, I believe we could do something similar here. In the code base we would use `controller-runtime` created by the SDK and on test, we inject the new structure we would create.

**Comment by LCaparelli** [comment]
@ricardozanini get out of my head. I was thinking that too :-)
