### ISSUE TITLE
Refactor resource managers to return their struct, not the interface

### ISSUE THREAD

**Issue by LCaparelli** [m88i/nexus-operator#109]
When creating a new resource manager today we return its interface:

```go
func NewManager(nexus v1alpha1.Nexus, client client.Client) infra.Manager {
```

While this is fine at the moment, it goes against the ["Accept Interfaces Return Struct"](https://mycodesmells.com/post/accept-interfaces-return-struct-in-go) rule of thumb. Returning an interface brings no additional benefit, but it can reduce the code's flexibility by removing all of the object's behavior that's not explicitly defined in the interface.

For example, consider the following interface:

```go
type Person interface {
    Name() string
    Age() int
}
```

One implementation of that interface could be:

```go
type Gamer struct {
	name  string
	age   int
	games []Game
}

func (g Gamer) Name() string {
	return g.name
}

func (g Gamer) Age() int {
	return g.age
}

func (g Gamer) Games() []Game {
	return g.games
}
```
If the function that creates a new gamer returned `Person`, we could never access this additional behavior defined in `Games()`. If it returned `*Gamer`, we'd still be able to use functions which receive a `Person` as parameter, as `Gamer` implements that interface AND we'd still be able to make use of this type's specific behavior.

**Comment by ricardozanini** [comment]
That's true for public structures, but not for private ones that we **do want** to hide the additional behavior.

**Comment by LCaparelli** [comment]
> That's true for public structures, but not for private ones that we **do want** to hide the additional behavior and expose only the public interface.

That's a good point. But exposing the struct doesn't necessarily add new liberties to the user. If we expose the struct and keep its fields private, then the user will still depend on the methods we expose to actually use that type.

In this scenario we'd need to add nil checks on the methods to make sure we don't end up panicking for nil dereference, but I personally don't see that as a big negative effect, especially considering it would allow us to extend an object's behavior past the interface.

I feel that exposing only the interface reduces the API's flexibility by tightly coupling the struct behavior to a particular interface for no good reason (or at least I couldn't myself come with a counter-example). One of main benefits of OO in Go is how we don't need to forcefully bind a struct to an interface and as things are we're not making much use of this benefit.

On the Network Manager, for example, we could have a method that exposes to the caller whether or not routes are available, since we keep this information on the struct:

```go
type Manager struct {
	nexus  *v1alpha1.Nexus
	client client.Client

	routeAvailable, ingressAvailable, ocp bool
}

func (m Manager) RouteAvailable() bool {
	return m.routeAvailable
}
```

But if whenever we create a new manager we return the `infra.Manager` interface, the user would not be able to make use of such method as it's not part of the interface. If we returned the `Manager` struct instead, they could use it as `infra.Manager` AND would still be able to easily check if routes are available.

Wdyt?

**Comment by ricardozanini** [comment]
I'm not against it. But if I'm a caller and I see in my IDE things like `infra.Manager` I'll try to `manager := infra.Manager{}`. That's a UX problem from the caller pov.

If you want to expose such interfaces, just add the methods to the interface instead. I can see benefits of this method without having to rely on builders. For example, either creating the instance with `manager := infra.Manager{}` or `manager :=infra.NewManager{}`.

**Comment by LCaparelli** [comment]
> I'm not against it. But if I'm a caller and I see in my IDE things like infra.Manager I'll try to manager := infra.Manager{}. That's a UX problem from the caller pov.

`infra.Manager` is actually the interface, but from context I assume you meant something like `manager := networking.Manager{}`. I agree that this reduces clarity for the user to a certain degree, but that user would soon see he can't do much with that empty struct. Also, this seems to be a pretty common pattern. See [apimachinery's implementation](https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/scheme.go) of the `runtime.Scheme` struct for example. All of its fields are left unexposed and its "constructor" function `NewScheme` returns a pointer to a struct that becomes useful after initialization through this function:

```go
// NewScheme creates a new Scheme. This scheme is pluggable by default.
func NewScheme() *Scheme {
	s := &Scheme{
		gvkToType:                 map[schema.GroupVersionKind]reflect.Type{},
		typeToGVK:                 map[reflect.Type][]schema.GroupVersionKind{},
		unversionedTypes:          map[reflect.Type]schema.GroupVersionKind{},
		unversionedKinds:          map[string]reflect.Type{},
		fieldLabelConversionFuncs: map[schema.GroupVersionKind]FieldLabelConversionFunc{},
		defaulterFuncs:            map[reflect.Type]func(interface{}){},
		versionPriority:           map[string][]string{},
		schemeName:                naming.GetNameFromCallsite(internalPackages...),
	}
```

> If you want to expose such interfaces, just add the methods to the interface instead. I can see benefits of this method without having to rely on builders. For example, either creating the instance with manager := infra.Manager{} or manager :=infra.NewManager{}.

Well, that's precisely the point I was trying to make in my previous comment: you **can't** just add this new behavior to the interface, because it only belongs to that particular type, it's not a behavior shared across all managers. The deployment manager is not aware if routes are available or not, only the network manager is. We couldn't add these specific behaviors to the interface because they are not common to all managers.

**Comment by ricardozanini** [comment]
OK, go ahead! :)
