### ISSUE TITLE
Provide a way to specify a separate PVC for the blob store

### ISSUE THREAD

**Issue by titou10titou10** [m88i/nexus-operator#201]
The operator allows to specify only one PVC for the whole installation 

As a nexus repository administrator, I would like to have the possibility to specify a specific PVC for blobs (mounted in`"/nexus-data/blobs"` or elsewhere), distinct from the nexus installation. This for many reasons, including data size, storage speed, different backup specs etc.

**Would you be able to assist in testing this feature if implemented?**
yes

**Comment by LCaparelli** [comment]
Thanks for this as well @titou10titou10, also looks like a good one.

We can manipulate blob store config via the [REST API](https://help.sonatype.com/repomanager3/rest-and-integration-api/blob-store-api). This is something we'd deal with at [m88i/aicura](https://github.com/m88i/aicura), but from what I read in [doc](https://help.sonatype.com/repomanager3/high-availability/configuring-blob-stores), "By default, a file blob store named default is automatically created in the directory $data-dir/blobs/default during installation". 

So it doesn't look like we can prevent this default one from being created in the first place. I don't see any harm in keeping the default store in the same PVC as the installation, but allowing users to specify PVCs containing additional stores. Would that be ok for your use case @titou10titou10?

**Comment by titou10titou10** [comment]
@LCaparelli the question is not about creation blobs store in nexus or disabling the creation of the default one, the question is to be able to have the possibility to create extra PVC via the operator to held multiple blob store, or at a minimum (my request), mount the $data-dir/blobs directory in a PVC separated from the general PVC

There are backup tools, like [velero](https://velero.io/), that perfoms backups based on PVC and usually, you don't want to backup the blob directories that contains artifacts from proxy servers that can easily be recreated (ie dockerhub, maven central etc) but only your own blobs

When you install nexus with Helm, you can add extra volumes/PVC as you wish  . This is what we are curently doing when installing nexus via Helm, ie create one blob storage per repository, each one in its own directory mounted from a volume/PVC specified in values.yaml. So we backup only PVC that held usefull data. And also we set the PVC for some repository on faster storage class depending on the usage

This RFE is to enahnce the nexus CR to allow to define extra volume/PVC mounted in the deployment

**Comment by LCaparelli** [comment]
Sorry @titou10titou10 , seems that I was not clear in my previous comment.

Yes, I agree we should allow users to specify additional stores. Quick research indicates this should be achievable, but I was concerned with whether keeping the default store intact would be a problem. The reason why I also mentioned the REST API is because thought it would be nice if the store config was automatically created, not only mounting the PVC, but configuring Nexus to use it.

From what you just said, it seems like additional stores (without touching the default store) would address your use case nicely.

**Comment by ricardozanini** [comment]
@LCaparelli this should be very simple to implement, actually. I'd say to add a new option in the `storage` attribute for the Nexus type with additional PVCs. So users could easily map/create whichever they want and attach to the Nexus server being deployed. I think we can work on both RFEs from @titou10titou10 for 0.6.0. wdyt?

**Comment by LCaparelli** [comment]
> @LCaparelli this should be very simple to implement, actually. I'd say to add a new option in the storage attribute for the Nexus type with additional PVCs.

My initial plan was to have the Operator also configuring the blob storage definitions on the Nexus server as well, not only associating the additional PVCs with the deployment. In hindsight, that might not be the best way forward: the core functionality here is to allow mounting additional PVCs.

Configuring blob stores (regardless of  additional PVCs or not) would be a better fit for a separate issue (and API), and AFAICT a better design choice as well, with higher cohesion.

> I think we can work on both RFEs from @titou10titou10 for 0.6.0. wdyt?

Yes, I think so too. :-)

**Comment by ricardozanini** [comment]
I think I'll add additional PVCs to the interface to allow use case likes this and then we can open a follow up issue to use the API instead and configure blobs. But I'd rather wait to see more concrete use cases for the API usage as well.

**Comment by ricardozanini** [comment]
Related documentation: https://help.sonatype.com/repomanager3/repository-management/storage-guide
