### ISSUE TITLE
Feature request: allow setting settings in nexus.properties (feature flags, etc)

### ISSUE THREAD

**Issue by ibotty** [m88i/nexus-operator#204]
**Is your feature request related to a problem? Please describe.**
Feature Request to make  it possible to set properties traditionally set in a nexus.properties file.

It would be great have a setting in the CRD where one could set them.  But any way would be fine.

I need the feature flag `nexus.conan.hosted.enabled=true` (from https://issues.sonatype.org/browse/NEXUS-23629).

**Comment by ricardozanini** [comment]
Hi! Thanks for opening this issue! I need to wrap up some issues to release 0.6. I'll definitely add this one to the planning.
What about a configMap mapped to this property file?

**Comment by ibotty** [comment]
A `ConfigMap` would work as well.

**Comment by ibotty** [comment]
No pressure, but do you have an estimate on when v0.6.0 with that feature might be released?

I might find time to add the feature myself if you could give me a hint on where to start and what's necessary.  I am not familiar with OperatorSDK.

**Comment by ricardozanini** [comment]
Hey @ibotty! I'm currently working on it. We will probably ship 0.6.0 with only this feature for you :)
I'll have more to share by the end of the week.

**Comment by ibotty** [comment]
Uiuiui.  I am flattered!  Looking forward to it.

**Comment by ricardozanini** [comment]
Might help: https://blog.questionable.services/article/kubernetes-deployments-configmap-change/

**Comment by ibotty** [comment]
Yeah,  I know about that feature.  That was missing (not only because of configmap changes).

**Comment by ricardozanini** [comment]
Oh that's a reference for myself :)

**Comment by ricardozanini** [comment]
@ibotty are you able to test the feature if I build an image for you? See #212

**Comment by ibotty** [comment]
Yes, but I am not sure exactly how, because I am running the operator from OLM, andI don't know how to actually use another image.  I will try to find a way though.

**Comment by ricardozanini** [comment]
hmmm, you can [install it manually](https://github.com/m88i/nexus-operator/#quick-install) in a local environment and update the `Deployment` image with the one I'll build for you.

**Comment by ibotty** [comment]
Well, yes.  I can certainly test it.

**Comment by ricardozanini** [comment]
@ibotty sorry for taking so long, I have a limited time to work on this operator. Can you try in your environment? Just apply this file:
https://gist.github.com/ricardozanini/b59ebc4b5267ddcb91abcdf5e9d270d7

Please use a test environment where you don't have the Nexus Operator installed.

Also see #212 for further discussions. There's an update in the README explaining how to configure your Nexus server using `Spec.Properties` field in your CR.
