### ISSUE TITLE
Provide a way to specify user-defined ingress annotations

### ISSUE THREAD

**Issue by andrey-yakubovskiy** [m88i/nexus-operator#205]
**Is your feature request related to a problem? Please describe.**
Currently, it's not possible to define custom annotations for ingress object.

**Describe the solution you'd like**
It should be possible to add user-defined annotations to ingress object. For example, to configure oauth2, whitelist source ips, etc.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you be able to assist in testing this feature if implemented?**
Yes

**Comment by ricardozanini** [comment]
Relates #200
