### ISSUE TITLE
Rewrite comparator logic

### ISSUE THREAD

**Issue by LCaparelli** [m88i/nexus-operator#39]
Currently the comparator is not using custom comp functions, which leads to changes in Ingress (which doesn't have a default comparator) to be left unaddressed. We could wrap the comparator with a builder to point to our own comp functions, such as in the [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator/blob/master/pkg/framework/comparator.go).

This also increases our control over this part of the reconcile loop, which can prove to be useful in the long run.

**Comment by ricardozanini** [comment]
should we fix this for 0.2.0?

**Comment by LCaparelli** [comment]
Hey @ricardozanini do you still think this is necessary after #55 was resolved by shifting comparison responsibility to the resource managers?

**Comment by ricardozanini** [comment]
I don't think so. We might close this one. :)
