### ISSUE TITLE
Add OLM image in CI cache to avoid pulling it all the time

### ISSUE THREAD

**Issue by ricardozanini** [m88i/nexus-operator#76]
Today we had an outage in Quay repository, which had a great impact in our CI since we pull the OLM image from it. 

Would be better to cache this image with Docker service and load it every time instead of pulling it. Will decrease our CI processing time and will also prevent our workflow to face problems like this in the future. 

Link for the outage: https://status.quay.io/incidents/kw2627bsdwd9

**Comment by Kaitou786** [comment]
Should this be done? I mean we can cache the `quay.io/operator-framework/upstream-registry-builder:v1.5.6` as it is pinned down to the specific tag but the operator-testing image we are fetching the latest tag, if we cache it we might not have the latest updated image?

**Comment by ricardozanini** [comment]
> Should this be done? I mean we can cache the `quay.io/operator-framework/upstream-registry-builder:v1.5.6` as it is pinned down to the specific tag but the operator-testing image we are fetching the latest tag, if we cache it we might not have the latest updated image?

We can have the cache to keep it for one day only. This is not a priority, tho.

**Comment by ricardozanini** [comment]
Never happened again, closing,
