### ISSUE TITLE
Allow the user to select the Pull Policy

### ISSUE THREAD

**Issue by LCaparelli** [m88i/nexus-operator#83]
**Is your feature request related to a problem? Please describe.**
At the moment the Pull Policy is hardcoded as "Always", meaning the user has no choice whether or not to pull an image.

**Describe the solution you'd like**
It would be nice if the user could select the policy as they see fit.

**Describe alternatives you've considered**
There could be a new field in the Nexus CRD to control this.

**Additional context**
N/A

**Would you be able to assist in testing this feature if implemented?**
Yes :grin:

**Comment by Kaitou786** [comment]
@LCaparelli IIRC if we remove the `ImagePullPolicy` from `controller>nexus>resource>deployment>deployment.go` as it is an optional parameter, it'll be configured to `Always` in case of `latest tag` and `IfNotPresent` if any other tag is present. Do you think this'll be enough or do we want to take the input from user only?

**Comment by ricardozanini** [comment]
Good point, @Kaitou786 
I believe we can remove the parameter, leaving it as optional like you said, add a section in the README pointing that, but also add this parameter in the CRD in case the user wishes to override the default behavior.

Some users close the cluster access to third party registers, pushing themselves the images to the internal registry. In cases like this, they won't want to make the cluster to `Always` pull the image.

**Comment by Kaitou786** [comment]
Ah yes, so only set this parameter when user have defined it in the rescource spec.

**Comment by LCaparelli** [comment]
@Kaitou786 nice catch, I believe we should always defer to Kubernetes default behavior when possible.

@ricardozanini I like that idea a lot.

So we're all on the same page: the default behavior will be to simply not define `ImagePullPolicy` when creating the Deployment. If the user has not specified `spec.image` (which should be the full image with tag) or if they set `spec.useRedHatImage` as true, the resulting behavior will be an `Always` policy as the default images are constants defined in `pkg/controller/nexus/resource/deployment/manager.go`:

```go
    nexusCommunityLatestImage       = "docker.io/sonatype/nexus3:latest"
    nexusCertifiedLatestImage       = "registry.connect.redhat.com/sonatype/nexus-repository-manager"
```

The Red Hat image has no tag, so "latest" is used when pulling it (unless I'm missing something).

On the other hand, if the user defines an image, the pull policy will depend on whether they are using the "latest" tag or not. `Always` if so and `IfNotPresent` otherwise.

Finally, the user may directly configure the policy through the Nexus CR, which will override the default behavior regardless of the used image and tag.

Sounds good @ricardozanini @Kaitou786?

**Comment by ricardozanini** [comment]
Sounds awesome to me.

**Comment by Kaitou786** [comment]
That sounds perfect.
