### ISSUE TITLE
Improve install scripts or change README file

### ISSUE THREAD

**Issue by Kaitou786** [m88i/nexus-operator#99]
**Is your feature request related to a problem? Please describe.**
Today when the user clones the project and just run `make install` the nexus deployment fails as the image with 0.3.0 doesn't exist on quay, user can edit the deployment and change the image tag to run the pod

**Describe the solution you'd like**
User should not edit anything just running the `make install` should get the deployment running

**Describe alternatives you've considered**
1. Change the tag in deployment file
2. Instruct user to download repo from releases page
3. We can have modify install.sh script to accept the tag/version of image and checkout the repository at that tag, this tag can have default value of latest release (Currently 0.2.1)
**Additional context**
None

**Would you be able to assist in testing this feature if implemented?**
Yes

**Comment by ricardozanini** [comment]
@Kaitou786 are you going to send a PR to this one?

**Comment by Kaitou786** [comment]
@ricardozanini Yes I'll I just wanted to discuss and see which approach do you think is best

**Comment by ricardozanini** [comment]
If we can do this in an automatic matter (the install script to discover the latest version and install it), I'd say 3 as well. If not, I'd go with 2.

@LCaparelli wdyt?

**Comment by LCaparelli** [comment]
I like 3 too! If we can't get that working, we can also keep the master branch with the "latest" tag while each release branch points to the same release tag.

**Comment by Kaitou786** [comment]
@LCaparelli I think tags are better than branching for every minor release, IMO we can have branches for every major release and tags for minor ones. 
For 3rd way, I thought of two ways.
a.) checkout the repository at the tagged commit, i.e our current latest release is 0.2.1 which is tagged so we can have a step `git checkout tags/v0.2.1`  we can have the default value as the latest tag but user can also pass the version he want as a parameter e.g.: `(make install v0.2.0)`
b.) Fetch the latest available image on quay in the script and on the master branch itself and only change the image tag in `deploy/operator.yaml`
@ricardozanini @LCaparelli which one do you guys think should be implemented `a` or `b`. IMO `a` is better

**Comment by ricardozanini** [comment]
> EDIT: just realized we don't really have branches per release. @ricardozanini @Kaitou786 think we should have those?

We only branch if we would launch a minor fix for a major version, not otherwise. Since we are on Beta stage, I'd say to just go for the next version and keep coming. Aligning branches are a PITA.

@Kaitou786 you would need to fetch for the latest tag in our repo. I believe GH has an api or a URL in the repo to fetch for the latest one. Take a look on the badge that we have in the README.md to figure that out. It's pretty simple, I believe.

**Comment by Kaitou786** [comment]
@ricardozanini ah yes that is better, I'll do this and send the PR sometime tomorrow =D

**Comment by LCaparelli** [comment]
> @LCaparelli I think tags are better than branching for every minor release, IMO we can have branches for every major release and tags for minor ones.

I was thinking something similar, see below.

> We only branch if we would launch a minor fix for a major version, not otherwise. Since we are on Beta stage, I'd say to just go for the next version and keep coming. Aligning branches are a PITA.

While we're on 0.x I agree. As for when we're out of beta I like the release cycle RHEL has, which branches at every minor ("y" in "x.y.z") but also keeps a z stream which cherry picks commits which has been made to the next Y stream before its release (think urgent stuff, like security fixes). Maybe branches for the Y stream and tags for Z streams.

We really should discuss this on another issue when this actually becomes a problem, but just food for thought until then. :-)

>  I believe GH has an api or a URL in the repo to fetch for the latest one.

That's pretty cool :rocket:
